---
new_page_extension: md
auto_deploy: true
admin_path: editor
webhook_url: 
collections: 
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
